### ISSUE TITLE
Prompt Engineering within the RAG Pattern

### ISSUE THREAD

**Issue by raymond-nassar** [microsoft/rag-experiment-accelerator#12]
Should include prompt templates within the RAG Experiment Accelerator to allow the user to experiment.
Current prompt templates are located in `llm\prompts.py`
```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/rag-experiment-accelerator/issues/24
- [ ] https://github.com/microsoft/rag-experiment-accelerator/issues/26
- [ ] https://github.com/microsoft/rag-experiment-accelerator/issues/25
```
