### ISSUE TITLE
Implement Search Evaluator while querying

### ISSUE THREAD

**Issue by rasavant-ms** [microsoft/rag-experiment-accelerator#13]
Need to evaluate the search response from Azure Cognitive Search to determine its information retrieval accuracy. A score for response relevancy should be included as part of the tooling for this section.

https://learn.microsoft.com/en-us/azure/search/search-pagination-page-layout

https://learn.microsoft.com/en-us/azure/search/index-similarity-and-scoring

Search metrics that should be included:

- precision@k
- recall@k
- map@k

```[tasklist]
### Tasks
- [x] evaluate search score format
- [x] persist search score
- [x] display search score in mlflow
```
