### ISSUE TITLE
Load the RAG Experiment Accelerator as a library within Prompt Flow

### ISSUE THREAD

**Issue by raymond-nassar** [microsoft/rag-experiment-accelerator#154]
Create the DAG files which call the individual scripts within the RAG Experiment Accelerator into Prompt Flow.

[Context from prior design discussion](https://microsoft.sharepoint.com/:v:/t/KrakenLLMMVE/Ec9UtPqHvWtKrTN1nQnL8EgB2vYjOsJAo-IKDtRtZfQETg?nav=eyJwbGF5YmFja09wdGlvbnMiOnsic3RhcnRUaW1lSW5TZWNvbmRzIjo3NDIuMTg2LCJ0aW1lc3RhbXBlZExpbmtSZWZlcnJlckluZm8iOnsic2NlbmFyaW8iOiJDaGFwdGVyU2hhcmUiLCJhZGRpdGlvbmFsSW5mbyI6eyJpc1NoYXJlZENoYXB0ZXJBdXRvIjp0cnVlLCJzaGFyZWRDaGFwdGVyU291cmNlIjoiQUNTX01lZXRpbmdNaW51dGVzOiJ9fX0sInJlZmVycmFsSW5mbyI6eyJyZWZlcnJhbEFwcCI6IlN0cmVhbVdlYkFwcCIsInJlZmVycmFsVmlldyI6IlNoYXJlQ2hhcHRlckxpbmsiLCJyZWZlcnJhbEFwcFBsYXRmb3JtIjoiV2ViIiwicmVmZXJyYWxNb2RlIjoidmlldyJ9fQ&e=xFx6G0)

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/rag-experiment-accelerator/issues/172
- [x] https://github.com/microsoft/rag-experiment-accelerator/issues/173
- [x] https://github.com/microsoft/rag-experiment-accelerator/issues/174
- [x] https://github.com/microsoft/rag-experiment-accelerator/issues/175
- [x] https://github.com/microsoft/rag-experiment-accelerator/issues/176
- [x] Build an image
- [x] add rag_accelerator custom environment creation process
```
