### ISSUE TITLE
Enable search_config.json to configure the RAG parameters in the Standard Flow

### ISSUE THREAD

**Issue by raymond-nassar** [microsoft/rag-experiment-accelerator#155]
[Context from prior design discussion, with the most relevant part starting at 21:10](https://microsoft.sharepoint.com/:v:/t/KrakenLLMMVE/Ec9UtPqHvWtKrTN1nQnL8EgB2vYjOsJAo-IKDtRtZfQETg?nav=eyJwbGF5YmFja09wdGlvbnMiOnsic3RhcnRUaW1lSW5TZWNvbmRzIjoxMDk3Ljc2NiwidGltZXN0YW1wZWRMaW5rUmVmZXJyZXJJbmZvIjp7InNjZW5hcmlvIjoiQ2hhcHRlclNoYXJlIiwiYWRkaXRpb25hbEluZm8iOnsiaXNTaGFyZWRDaGFwdGVyQXV0byI6dHJ1ZSwic2hhcmVkQ2hhcHRlclNvdXJjZSI6IkFDU19NZWV0aW5nTWludXRlczoifX19LCJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJTdHJlYW1XZWJBcHAiLCJyZWZlcnJhbFZpZXciOiJTaGFyZUNoYXB0ZXJMaW5rIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXcifX0&e=fvqS1Q)

- Research spike - How to add parameters to PromptFlow
- Design discussion with team and async sign-off
- Implement all parameters from search_config to this.
- Documentation
```[tasklist]
### Tasks
- [x] Update REAMDME to reference section on search_config settings in root folder.
- [x] Design discussion with team and async sign-off
- [x] Implement all parameters from search_config to this.
- [x] Research spike - How to add parameters to PromptFlow
```
