### ISSUE TITLE
Storage and Retrieval of Secrets

### ISSUE THREAD

**Issue by raymond-nassar** [microsoft/rag-experiment-accelerator#156]
[Context from a prior discussion meeting.](https://microsoft.sharepoint.com/:v:/t/KrakenLLMMVE/Ec9UtPqHvWtKrTN1nQnL8EgB2vYjOsJAo-IKDtRtZfQETg?nav=eyJwbGF5YmFja09wdGlvbnMiOnsic3RhcnRUaW1lSW5TZWNvbmRzIjo5NzIuNDI2LCJ0aW1lc3RhbXBlZExpbmtSZWZlcnJlckluZm8iOnsic2NlbmFyaW8iOiJDaGFwdGVyU2hhcmUiLCJhZGRpdGlvbmFsSW5mbyI6eyJpc1NoYXJlZENoYXB0ZXJBdXRvIjp0cnVlLCJzaGFyZWRDaGFwdGVyU291cmNlIjoiQUNTX01lZXRpbmdNaW51dGVzOiJ9fX0sInJlZmVycmFsSW5mbyI6eyJyZWZlcnJhbEFwcCI6IlN0cmVhbVdlYkFwcCIsInJlZmVycmFsVmlldyI6IlNoYXJlQ2hhcHRlckxpbmsiLCJyZWZlcnJhbEFwcFBsYXRmb3JtIjoiV2ViIiwicmVmZXJyYWxNb2RlIjoidmlldyJ9fQ&e=Ghln0Y)

Revisit context to update tasks below

```[tasklist]
### Tasks
- [x] Research spike - Using key vault in PF and environment variables in RAG repo
- [x] Write a script to store the secrets related to the LLM API and ACS into Key Vault
- [x] Retrieve the secrets from Key Vault for usage within the Prompt Flow DAG
```
