### ISSUE TITLE
Eng Fundamentals: Unit test coverage from 16% to 50%

### ISSUE THREAD

**Issue by raymond-nassar** [microsoft/rag-experiment-accelerator#229]
```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/rag-experiment-accelerator/issues/247
- [ ] https://github.com/microsoft/rag-experiment-accelerator/issues/246
- [ ] https://github.com/microsoft/rag-experiment-accelerator/issues/36
- [ ] https://github.com/microsoft/rag-experiment-accelerator/issues/261
```
