### ISSUE TITLE
Azure ML pipeline

### ISSUE THREAD

**Issue by guybartal** [microsoft/rag-experiment-accelerator#326]
Implement running the steps of RAG Experiment Accelerator in an AzureML pipeline. 

This will achieve:
- Being able to start several experiments in parallel, rather than sequentially
- Perform the indexing step of an experiment in parallel, as this is the slowest step 

Design diagram
![AzureMLPipeline drawio](https://github.com/microsoft/rag-experiment-accelerator/assets/52954123/c0417527-4b4e-44e0-9c93-83aead42c726)

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/rag-experiment-accelerator/issues/342
- [ ] https://github.com/microsoft/rag-experiment-accelerator/issues/413
- [ ] https://github.com/microsoft/rag-experiment-accelerator/issues/402
- [ ] https://github.com/microsoft/rag-experiment-accelerator/issues/403
- [ ] https://github.com/microsoft/rag-experiment-accelerator/issues/411
- [ ] https://github.com/microsoft/rag-experiment-accelerator/issues/435
```
