### ISSUE TITLE
 Part 1: Bicep script to add resources to isolated network

### ISSUE THREAD

**Issue by jedheaj314** [microsoft/rag-experiment-accelerator#344]
# Requirements:

- Implement ability to deploy azure resources for RAG accelerator in isolated network [Part 1]
- Implement ability access the RAG accelerator resources that are deployed in isolated network [[Part 2](https://github.com/microsoft/rag-experiment-accelerator/issues/466)]

# Use cases:

### 1. Private network for azure resources:

As an engineer, I want to building an environment for RAG experiments, 
I want to use a Bicep template to provision an environment so that Azure OpenAI endpoint, Azure Machine learning workspace and Search AI endpoints are accessible only via a specific virtual network.

 ### 2. Virtual machine to manage resources on vnet

As an engineer, 
I want to build an environment for RAG experiments, 
I want to use a Bicep template to provision an environment with a virtual machine using which I can manage my Azure services - Azure OpenAI endpoint, Azure Machine learning workspace and Search AI accessible only via a specific virtual network.

### 3. configure and execute experiments (via vnet)

As an engineer/data scientist, 
I want to build an environment for RAG experiments, 
I want to use a Bicep template to provision an environment with a virtual machine using which I can configure and execute my experiments using RAG Experiment Accelerator using Azure services - Azure OpenAI endpoint, Azure Machine learning workspace and Search AI accessible only via a specific virtual network.

### 4. View jobs and compare experiments (via vnet)
 
As a data scientist, 
I want to build an environment for RAG experiments, 
I want to use a Bicep template to provision an environment with a virtual machine using which I can view jobs and compare experiments using Azure Azure Machine learning workspace accessible only via a specific virtual network.

# Design

[Design Diagram](https://microsofteur-my.sharepoint.com/:u:/g/personal/ajedhe_microsoft_com/EWVh06nARutLsTpenFT0-TEBjJLwLVl0WrcBtpAHmTrsLQ?e=v0eico)

# Other Information:

List of all resources that are deployed using bicep at the moment:

1. Azure Open AI 
3. Azure Search Service
4. Storage Account
5. Key Vault
6. Monitoring (Application Insight)
7. Machine Learning Workspace 
8. Container registry

### Questions

Which resources we want to deploy in the VNET from above?
=> all
RAG architecture design?
=>
Subnet:
Number of subnets?
=> 1 subnet for resources
=> 1 subnet to manage resources (jump box)

Address space allocation?
=> whatever is best
Do we need any other isolations?
=> no

Private endpoint:
Will the resources required private access?
=> yes

Any other considerations and special configurations needed?
=> No (general)

### Assumptions:
- Will be deploying using same permissions as current bicep does
- Will be deploying to same target as the current bicep
- No changes needed  to deployment process

# Other required work:
- Switch for vnet or without

# Out of scope:
- Access management configuration is part of Task [Part 2](https://github.com/microsoft/rag-experiment-accelerator/issues/466)

# Note:

This work is divided into 2 parts.
Part 1 is completed under this ticket.
and Part 2 is [here](https://github.com/microsoft/rag-experiment-accelerator/issues/466)

Part 1 is for adding optional network isolation for the RAG resources and Part 2 is for providing a way for a host developer to access the private networked resources.

# Part 1 - tasks

```[tasklist]
### Tasks
- [x] New bicep script to deploy resources in isolated network given required network configurations.
- [x] Changes to ```infra/main.bicep``` to conditionally call network isolation bicep script with resources to be deployed in isolation.
- [x] Environment variables in template needed to deploy resources in isolated network: network names and address spaces.
```
