### ISSUE TITLE
Add test coverage to the core functions

### ISSUE THREAD

**Issue by shanepeckham** [microsoft/rag-experiment-accelerator#36]
```[tasklist]
### Tasks
- [x] https://github.com/microsoft/rag-experiment-accelerator/issues/253
- [x] https://github.com/microsoft/rag-experiment-accelerator/issues/254
- [x] https://github.com/microsoft/rag-experiment-accelerator/issues/255
- [x] https://github.com/microsoft/rag-experiment-accelerator/issues/256
- [x] https://github.com/microsoft/rag-experiment-accelerator/issues/257
- [x] https://github.com/microsoft/rag-experiment-accelerator/issues/258
```
