### ISSUE TITLE
adding metadata for documents loaded in a central module / class

### ISSUE THREAD

**Issue by guybartal** [microsoft/rag-experiment-accelerator#434]
Loaded documents should get indexes in Azure Search with metadata which contains the source filename so we could serve those files later on in a chat webapp.
Currently only `customJsonLoader.py` implements that logic.
```[tasklist]
### Tasks
- [x] Add filename for htmlLoader
- [x] Add filename for docxLoader
- [x] Add filename for pdfLoader
- [x] Add filename for textLoader
- [x] Add filename for markdownLoader
- [x] Add filename for documentIntelligenceLoader
```
