### ISSUE TITLE
Log all config hyper parameters to mlflow tags

### ISSUE THREAD

**Issue by guybartal** [microsoft/rag-experiment-accelerator#480]
As a researcher I would like all my `config.json` hyper parameters logged as `mlflow` tags as soon as possible
So, I would be able to compare between my job runs even if pipeline didn't finish to run (failed / long time running).

note:
today only few properties are being tagged in mlflow and many parameters are missing.
```[tasklist]
### Tasks
- [ ] Remove hardcoded mlfow tags
- [ ] Log all config.json and index_config properties as flat mlflow tags
- [ ] Log mlflow tags per step and not only in eval step
```
