### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by rasavant-ms** [microsoft/rag-experiment-accelerator#54]
Add documentation to explain:

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/rag-experiment-accelerator/issues/100
- [ ] https://github.com/microsoft/rag-experiment-accelerator/issues/101
- [ ] https://github.com/microsoft/rag-experiment-accelerator/issues/102
- [ ] https://github.com/microsoft/rag-experiment-accelerator/issues/19
- [ ] https://github.com/microsoft/rag-experiment-accelerator/issues/129
- [ ] https://github.com/microsoft/rag-experiment-accelerator/issues/130
```
