### ISSUE TITLE
Enforce json schema for config.json

### ISSUE THREAD

**Issue by guybartal** [microsoft/rag-experiment-accelerator#543]
As a user I want to know that I've configured my experiment correctly and know the possible values per setting
So the experiment will fail fast and not in the middle of a long run.

```[tasklist]
### Tasks
- [ ] add [jsonschema](https://pypi.org/project/jsonschema/) package
- [ ] create json schema for all possible values for config.json
- [ ] validate json schema and throw an error upon running any step
- [ ] validate json schema upon pre-commit for sample and ci configuration
```

Technical Notes:

- https://www.linkedin.com/pulse/mastering-json-schema-validation-python-developers-guide-singh-ebffc/
