### ISSUE TITLE
Read a PDF file and if it has images then it should be converted into embededdings and stored with AI Search

### ISSUE THREAD

**Issue by ritesh-modi** [microsoft/rag-experiment-accelerator#725]
```[tasklist]
### Tasks
- [ ] Read PDF file
- [ ] Extract images from the file
- [ ] Read all pdf files from a folder
- [ ] Extract all the information from images and convert them into embeddings
- [ ] Store both the text and embeddings from images into AI Search
- [ ] While storing the text into AI Search, the text should overlapp with prior and next paragraph
- [ ] Test it by querying the Index
- [ ] https://github.com/microsoft/rag-experiment-accelerator/issues/727
- [ ] https://github.com/microsoft/rag-experiment-accelerator/issues/729
```
